 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/campi", type: :request do
  # Campus. As you add validations to Campus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Campus.create! valid_attributes
      get campi_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      campus = Campus.create! valid_attributes
      get campus_url(campus)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_campus_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      campus = Campus.create! valid_attributes
      get edit_campus_url(campus)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Campus" do
        expect {
          post campi_url, params: { campus: valid_attributes }
        }.to change(Campus, :count).by(1)
      end

      it "redirects to the created campus" do
        post campi_url, params: { campus: valid_attributes }
        expect(response).to redirect_to(campus_url(Campus.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Campus" do
        expect {
          post campi_url, params: { campus: invalid_attributes }
        }.to change(Campus, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post campi_url, params: { campus: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested campus" do
        campus = Campus.create! valid_attributes
        patch campus_url(campus), params: { campus: new_attributes }
        campus.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the campus" do
        campus = Campus.create! valid_attributes
        patch campus_url(campus), params: { campus: new_attributes }
        campus.reload
        expect(response).to redirect_to(campus_url(campus))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        campus = Campus.create! valid_attributes
        patch campus_url(campus), params: { campus: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested campus" do
      campus = Campus.create! valid_attributes
      expect {
        delete campus_url(campus)
      }.to change(Campus, :count).by(-1)
    end

    it "redirects to the campi list" do
      campus = Campus.create! valid_attributes
      delete campus_url(campus)
      expect(response).to redirect_to(campi_url)
    end
  end
end
