 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/carona_paradas", type: :request do
  # CaronaParada. As you add validations to CaronaParada, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CaronaParada.create! valid_attributes
      get carona_paradas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      carona_parada = CaronaParada.create! valid_attributes
      get carona_parada_url(carona_parada)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_carona_parada_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      carona_parada = CaronaParada.create! valid_attributes
      get edit_carona_parada_url(carona_parada)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CaronaParada" do
        expect {
          post carona_paradas_url, params: { carona_parada: valid_attributes }
        }.to change(CaronaParada, :count).by(1)
      end

      it "redirects to the created carona_parada" do
        post carona_paradas_url, params: { carona_parada: valid_attributes }
        expect(response).to redirect_to(carona_parada_url(CaronaParada.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CaronaParada" do
        expect {
          post carona_paradas_url, params: { carona_parada: invalid_attributes }
        }.to change(CaronaParada, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post carona_paradas_url, params: { carona_parada: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested carona_parada" do
        carona_parada = CaronaParada.create! valid_attributes
        patch carona_parada_url(carona_parada), params: { carona_parada: new_attributes }
        carona_parada.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the carona_parada" do
        carona_parada = CaronaParada.create! valid_attributes
        patch carona_parada_url(carona_parada), params: { carona_parada: new_attributes }
        carona_parada.reload
        expect(response).to redirect_to(carona_parada_url(carona_parada))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        carona_parada = CaronaParada.create! valid_attributes
        patch carona_parada_url(carona_parada), params: { carona_parada: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested carona_parada" do
      carona_parada = CaronaParada.create! valid_attributes
      expect {
        delete carona_parada_url(carona_parada)
      }.to change(CaronaParada, :count).by(-1)
    end

    it "redirects to the carona_paradas list" do
      carona_parada = CaronaParada.create! valid_attributes
      delete carona_parada_url(carona_parada)
      expect(response).to redirect_to(carona_paradas_url)
    end
  end
end
