 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/paradas", type: :request do
  # Parada. As you add validations to Parada, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Parada.create! valid_attributes
      get paradas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      parada = Parada.create! valid_attributes
      get parada_url(parada)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_parada_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      parada = Parada.create! valid_attributes
      get edit_parada_url(parada)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Parada" do
        expect {
          post paradas_url, params: { parada: valid_attributes }
        }.to change(Parada, :count).by(1)
      end

      it "redirects to the created parada" do
        post paradas_url, params: { parada: valid_attributes }
        expect(response).to redirect_to(parada_url(Parada.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Parada" do
        expect {
          post paradas_url, params: { parada: invalid_attributes }
        }.to change(Parada, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post paradas_url, params: { parada: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested parada" do
        parada = Parada.create! valid_attributes
        patch parada_url(parada), params: { parada: new_attributes }
        parada.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the parada" do
        parada = Parada.create! valid_attributes
        patch parada_url(parada), params: { parada: new_attributes }
        parada.reload
        expect(response).to redirect_to(parada_url(parada))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        parada = Parada.create! valid_attributes
        patch parada_url(parada), params: { parada: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested parada" do
      parada = Parada.create! valid_attributes
      expect {
        delete parada_url(parada)
      }.to change(Parada, :count).by(-1)
    end

    it "redirects to the paradas list" do
      parada = Parada.create! valid_attributes
      delete parada_url(parada)
      expect(response).to redirect_to(paradas_url)
    end
  end
end
